export const CPD_COURSES = [
    {
        id: '1',
        title: 'Fundamental Psychiatric Nursing',
        description: 'Comprehensive training on basic psychiatric nursing care, patient assessment, and evidence-based interventions in mental health settings.',
        duration: '5 Days',
        startDate: '2024-05-15',
        endDate: '2024-05-20',
        credits: '15 CME Hours',
        targetProfessionals: 'Nurses, Health Officers',
        mode: 'Onsite',
        fee: '2,500 ETB',
    },
    {
        id: '2',
        title: 'Advanced Psychopharmacology',
        description: 'In-depth study of neurobiology and the latest pharmacological treatments for complex mental health disorders. Focus on recent drug approvals.',
        duration: '3 Days',
        startDate: '2024-06-10',
        endDate: '2024-06-13',
        credits: '10 CME Hours',
        targetProfessionals: 'Psychiatrists, Medical Doctors',
        mode: 'Hybrid',
        fee: '3,500 ETB',
    },
    {
        id: '3',
        title: 'CBT for Anxiety Disorders',
        description: 'Practical clinical skills for implementing Cognitive Behavioral Therapy techniques specifically tailored for anxiety and stress-related conditions.',
        duration: '4 Weeks',
        startDate: '2024-07-01',
        endDate: '2024-07-28',
        credits: '20 CME Hours',
        targetProfessionals: 'Psychologists, Counselors',
        mode: 'Online',
        fee: '3,000 ETB',
    },
    {
        id: '4',
        title: 'mhGAP Training of Trainers',
        description: 'Master the Mental Health Gap Action Program (mhGAP) to scale up care for mental, neurological, and substance use disorders in primary health care.',
        duration: '5 Days',
        startDate: '2024-08-05',
        endDate: '2024-08-10',
        credits: '15 CME Hours',
        targetProfessionals: 'Senior Health Professionals',
        mode: 'Onsite',
        fee: 'Free (MOH Sponsored)',
    },
    {
        id: '5',
        title: 'Child & Adolescent Psychiatry',
        description: 'A specialized course focusing on developmental disorders, adolescent depression, and early intervention strategies for young patients.',
        duration: '3 Days',
        startDate: '2024-09-12',
        endDate: '2024-09-15',
        credits: '12 CME Hours',
        targetProfessionals: 'Psychiatrists, Pediatricians',
        mode: 'Hybrid',
        fee: '4,000 ETB',
    },
    {
        id: '6',
        title: 'Emergency Psychiatry & De-escalation',
        description: 'Essential de-escalation techniques, risk assessment, and legal protocols for managing acute psychiatric emergencies in clinical settings.',
        duration: '2 Days',
        startDate: '2024-10-20',
        endDate: '2024-10-22',
        credits: '8 CME Hours',
        targetProfessionals: 'All Clinical Staff',
        mode: 'Onsite',
        fee: '1,500 ETB',
    },
];
