export const CPD_COURSES = [
    {
        id: '1',
        title: 'Trauma and Stress Related Disorders',
        description: 'Comprehensive training on identifying and managing trauma-related conditions in specialized mental health settings.',
        duration: '3 Days',
        startDate: '2024-05-15',
        endDate: '2024-05-18',
        credits: '15 CEU',
        targetProfessionals: 'Psychiatrists, Nurses, Psychologists',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'Approved'
    },
    {
        id: '2',
        title: 'Management of Alcohol Related Disorders',
        description: 'Evidence-based protocols for detoxification, rehabilitation, and long-term management of alcohol use disorders.',
        duration: '3 Days',
        startDate: '2024-06-10',
        endDate: '2024-06-13',
        credits: '15 CEU',
        targetProfessionals: 'Addiction Specialists, Clinical Staff',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'Approved'
    },
    {
        id: '3',
        title: 'Good Medicine Dispensing Practice and Communication Skills',
        description: 'Enhancing pharmaceutical care standards and patient-provider communication in mental health pharmacy services.',
        duration: '3 Days',
        startDate: '2024-07-05',
        endDate: '2024-07-08',
        credits: '15 CEU',
        targetProfessionals: 'Pharmacists, Pharmacy Technicians',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'Approved'
    },
    {
        id: '4',
        title: 'Management of Epilepsy',
        description: 'Clinical guidelines for the diagnosis, pharmacotherapy, and psychosocial support for patients living with epilepsy.',
        duration: '3 Days',
        startDate: '2024-08-12',
        endDate: '2024-08-15',
        credits: '15 CEU',
        targetProfessionals: 'Neurologists, General Practitioners',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'Approved'
    },
    {
        id: '5',
        title: 'Ethics and Quality of Care for People with Mental Disorders',
        description: 'Focusing on human rights, ethical dilemmas, and quality assurance in psychiatric inpatient and outpatient care.',
        duration: '3 Days',
        startDate: '2024-09-20',
        endDate: '2024-09-23',
        credits: '15 CEU',
        targetProfessionals: 'All Healthcare Professionals',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'Approved'
    },
    {
        id: '6',
        title: 'Nursing Process in Psychiatric Nursing',
        description: 'Mastering the nursing process framework specifically applied to psychiatric patient care and documentation.',
        duration: '3 Days',
        startDate: '2024-10-15',
        endDate: '2024-10-18',
        credits: '15 CEU',
        targetProfessionals: 'Psychiatric Nurses',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'Approved'
    },
    {
        id: '7',
        title: 'Medico-Legal Issues in Mental Health Services',
        description: 'Understanding the legal framework, forensic psychiatry basics, and patient rights in Ethiopia.',
        duration: '3 Days',
        startDate: '2024-11-10',
        endDate: '2024-11-13',
        credits: '15 CEU',
        targetProfessionals: 'Legal Officers, Senior Clinicians',
        mode: 'Onsite',
        fee: '2,100 ETB',
        status: 'On-going'
    },
    {
        id: '8',
        title: 'Detection and Management of Dementia at Primary Health Care',
        description: 'Strengthening PHC capacity to early detect and manage neurocognitive disorders in the elderly.',
        duration: '2 Days',
        startDate: '2024-12-05',
        endDate: '2024-12-07',
        credits: '12 CEU',
        targetProfessionals: 'PHC Workers, GP, Health Officers',
        mode: 'Onsite',
        fee: '1,400 ETB',
        status: 'On-going'
    }
];
